(let ((base (if (or (eq system-type 'cygwin)
                    (eq system-type 'gnu/linux)
                    (eq system-type 'linux))
                    "/home/alex/Projects/emacs"
                    "C:/Users/Alex/Projects/emacs")))
  (add-to-list 'load-path base)
  (dolist (f (directory-files base))
    (let ((name (concat base "/" f)))
      (when (and (file-directory-p name) 
                 (not (equal f ".."))
                 (not (equal f ".")))
        (add-to-list 'load-path name)))))
(load "my-main")
